name: Publish to NPM

on:
  push:
    tags:
      - '@catalyst-ui-testing/*@*-canary.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - uses: actions/cache@v1
        id: cache-build
        with:
          path: '.'
          key: catalyst-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: catalyst-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - run: yarn validate
        env:
          CI: true
      - run: yarn test
        env:
          CI: true

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: catalyst-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        run: yarn canary:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
